### ISSUE TITLE
Uhhmm Idea is all red what did you do

### ISSUE THREAD

**Issue by StephenIsTaken** [StephenIsTaken/Raven-B4#4]
Every line is red and gives 98765414 errors

**Comment by Cosmic-SC** [comment]
WHAT THE F

**Comment by Cosmic-SC** [comment]
wait does the minecraft package work?

**Comment by Cosmic-SC** [comment]
u must do gradlew setupDecompWorkspace atleast once

**Comment by Cosmic-SC** [comment]
its probably the minecraft package that is not in the workspace

**Comment by Cosmic-SC** [comment]
ill check it tmrw just send a ss of any modules imports im too sleep deprived to understand anything rn

**Comment by Cosmic-SC** [comment]
also all i did was add lombok to build.gradle and configure MCP Accessor in the same file thats all

try using the orignal build.gradle from b++ and check if it fixes the issue. If it does not, then its ur workspace that has some problem

**Comment by StephenIsTaken** [comment]
> u must do gradlew setupDecompWorkspace atleast once

I did

**Comment by StephenIsTaken** [comment]
Probably fucked my workspace

**Comment by StephenIsTaken** [comment]
Me issue
